import { ComponentTemplate, DEFAULT_SECTION_HEADER } from '../types'

export const COMPONENT_TEMPLATES: ComponentTemplate[] = [
  {
    type: 'hero',
    label: '히어로 섹션',
    description: '타이틀, 설명, 버튼이 있는 메인 섹션',
    icon: '🎯',
  },
  {
    type: 'slider',
    label: '이미지 슬라이더',
    description: '여러 이미지를 슬라이드로 표시',
    icon: '🖼️',
  },
  {
    type: 'video',
    label: '비디오',
    description: 'YouTube 또는 직접 업로드 비디오',
    icon: '🎬',
  },
  {
    type: 'divider',
    label: '구분선',
    description: '섹션 구분을 위한 선 또는 여백',
    icon: '➖',
  },
  {
    type: 'grid',
    label: '그리드/리스트',
    description: '상품 목록, 스펙 테이블 등',
    icon: '📋',
  },
  {
    type: 'table',
    label: '표',
    description: '데이터를 표 형식으로 표시',
    icon: '📊',
  },
  {
    type: 'faq',
    label: 'FAQ/아코디언',
    description: '자주 묻는 질문을 접었다 펼 수 있는 형태',
    icon: '❓',
  },
  {
    type: 'tabs',
    label: '탭',
    description: '여러 정보를 탭으로 구분하여 표시',
    icon: '📑',
  },
  {
    type: 'cta',
    label: 'CTA 버튼',
    description: '구매하기, 문의하기 등 주요 액션 버튼',
    icon: '🔘',
  },
  {
    type: 'beforeAfter',
    label: 'Before/After',
    description: '드래그하여 비교하는 이미지 슬라이더',
    icon: '⚖️',
  },
  {
    type: 'countdown',
    label: '카운트다운',
    description: '세일 종료, 이벤트 마감 시간 표시',
    icon: '⏰',
  },
  {
    type: 'review',
    label: '리뷰/후기',
    description: '고객 후기를 캐러셀 형태로 표시',
    icon: '⭐',
  },
  {
    type: 'iconList',
    label: '아이콘 리스트',
    description: '아이콘과 텍스트로 특징 나열',
    icon: '✓',
  },
  {
    type: 'stickyBar',
    label: '스티키 하단바',
    description: '화면 하단에 고정되는 구매 버튼 바',
    icon: '📌',
  },
  {
    type: 'quote',
    label: '인용구/강조',
    description: '중요 문구를 강조하여 표시',
    icon: '💬',
  },
  {
    type: 'imageGallery',
    label: '이미지 갤러리',
    description: '썸네일과 줌 기능이 있는 이미지 갤러리',
    icon: '🔍',
  },
  {
    type: 'trustBadge',
    label: '신뢰 배지',
    description: '보안 인증, 결제 안전 등 신뢰 요소 표시',
    icon: '🛡️',
  },
  {
    type: 'shipping',
    label: '배송 정보',
    description: '배송비, 예상 도착일 등 배송 안내',
    icon: '🚚',
  },
  {
    type: 'noticeBanner',
    label: '공지 배너',
    description: '프로모션, 할인 정보 등 알림 배너',
    icon: '📢',
  },
]

// Default values for each component type
export const DEFAULT_HERO = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ffffff',
  showOverlayImage: false,
  overlayImage: '',
  showSectionTitle: true,
  sectionTitle: 'NEW ARRIVAL',
  sectionTitleColor: '#ffffff',
  sectionTitleBgColor: '#3b82f6',
  showTitle: true,
  title: '여기에 메인 타이틀을 입력하세요',
  titleSize: '48',
  titleWeight: '700',
  titleColor: '#000000',
  showDescription: true,
  description: '상세한 설명을 입력하세요',
  descriptionSize: '18',
  descriptionWeight: '400',
  descriptionColor: '#666666',
  descriptionAlign: 'center',
  descriptionLetterSpacing: '0',
  showDescriptionImage: false,
  descriptionImage: '',
  showButton: true,
  buttonText: '자세히 보기',
  buttonSize: '16',
  buttonWeight: '600',
  buttonColor: '#ffffff',
  buttonBgColor: '#000000',
  height: '600px',
  align: 'center',
  justify: 'center',
}

export const DEFAULT_SLIDER = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#f3f4f6',
  images: ['https://via.placeholder.com/1200x600/3b82f6/ffffff?text=Slide+1'],
  imageWidth: '1140px',
  height: '500px',
  autoPlay: false,
  interval: 3000,
  showIndicators: true,
}

export const DEFAULT_VIDEO = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#000000',
  videoType: 'youtube',
  videoUrl: '',
  height: '500px',
  autoPlay: false,
  muted: true,
  loop: false,
}

export const DEFAULT_DIVIDER = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: 'transparent',
  height: '40px',
  showLine: true,
  lineStyle: 'solid',
  lineColor: '#e5e7eb',
  lineWidth: '1px',
}

export const DEFAULT_GRID = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ffffff',
  itemBackgroundColor: '#ffffff',
  columns: 3,
  gap: '20px',
  iconSize: '80px',
  height: 'auto',
  items: [
    { id: '1', image: 'https://via.placeholder.com/80', title: '아이템 1', description: '설명 1' },
    { id: '2', image: 'https://via.placeholder.com/80', title: '아이템 2', description: '설명 2' },
    { id: '3', image: 'https://via.placeholder.com/80', title: '아이템 3', description: '설명 3' },
  ],
}

export const DEFAULT_TABLE = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ffffff',
  headerBackgroundColor: '#000000',
  headerTextColor: '#ffffff',
  cellBackgroundColor: '#ffffff',
  cellTextColor: '#000000',
  borderColor: '#e5e7eb',
  borderWidth: '1px',
  height: 'auto',
  columns: [
    { id: 'col1', label: '항목', width: '200px', textAlign: 'left' },
    { id: 'col2', label: '내용', width: 'auto', textAlign: 'left' },
  ],
  rows: [
    { id: 'row1', cells: ['항목 1', '내용 1'] },
    { id: 'row2', cells: ['항목 2', '내용 2'] },
  ],
}

export const DEFAULT_FAQ = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ffffff',
  height: 'auto',
  titleText: '자주 묻는 질문',
  titleSize: '28',
  titleWeight: '700',
  titleColor: '#000000',
  showTitle: true,
  questionColor: '#000000',
  questionBgColor: '#f9fafb',
  answerColor: '#666666',
  answerBgColor: '#ffffff',
  borderColor: '#e5e7eb',
  iconColor: '#000000',
  items: [
    { id: 'faq1', question: '질문 1을 입력하세요', answer: '답변 1을 입력하세요' },
    { id: 'faq2', question: '질문 2를 입력하세요', answer: '답변 2를 입력하세요' },
  ],
}

export const DEFAULT_TABS = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ffffff',
  height: 'auto',
  tabBgColor: '#f3f4f6',
  tabActiveColor: '#000000',
  tabTextColor: '#666666',
  tabActiveTextColor: '#ffffff',
  contentBgColor: '#ffffff',
  contentTextColor: '#333333',
  borderColor: '#e5e7eb',
  items: [
    { id: 'tab1', label: '상세정보', content: '상세정보 내용을 입력하세요' },
    { id: 'tab2', label: '리뷰', content: '리뷰 내용을 입력하세요' },
    { id: 'tab3', label: '배송안내', content: '배송안내 내용을 입력하세요' },
  ],
}

export const DEFAULT_CTA = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#3b82f6',
  height: 'auto',
  showTitle: true,
  title: '지금 바로 시작하세요',
  titleSize: '32',
  titleWeight: '700',
  titleColor: '#ffffff',
  showDescription: true,
  description: '특별한 혜택과 함께 지금 구매하세요',
  descriptionSize: '16',
  descriptionColor: '#e0e7ff',
  buttonText: '구매하기',
  buttonSize: '18',
  buttonWeight: '600',
  buttonColor: '#3b82f6',
  buttonBgColor: '#ffffff',
  buttonBorderRadius: '8px',
  buttonWidth: '200px',
}

export const DEFAULT_BEFORE_AFTER = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ffffff',
  height: 'auto',
  beforeImage: 'https://via.placeholder.com/600x400/ef4444/ffffff?text=Before',
  afterImage: 'https://via.placeholder.com/600x400/22c55e/ffffff?text=After',
  beforeLabel: 'Before',
  afterLabel: 'After',
  labelColor: '#ffffff',
  labelBgColor: '#000000',
  sliderColor: '#ffffff',
  imageHeight: '400px',
}

export const DEFAULT_COUNTDOWN = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ef4444',
  height: 'auto',
  targetDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 16),
  showTitle: true,
  title: '특가 세일 종료까지',
  titleSize: '24',
  titleWeight: '600',
  titleColor: '#ffffff',
  numberSize: '48',
  numberColor: '#ef4444',
  numberBgColor: '#ffffff',
  labelSize: '14',
  labelColor: '#ffffff',
  expiredMessage: '이벤트가 종료되었습니다',
}

export const DEFAULT_REVIEW = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#f9fafb',
  height: 'auto',
  showTitle: true,
  title: '고객 후기',
  titleSize: '28',
  titleWeight: '700',
  titleColor: '#000000',
  cardBgColor: '#ffffff',
  cardTextColor: '#333333',
  starColor: '#fbbf24',
  autoPlay: true,
  interval: 5000,
  items: [
    { id: 'review1', rating: 5, content: '정말 만족합니다! 품질이 좋고 배송도 빨라요.', author: '김**' },
    { id: 'review2', rating: 5, content: '재구매 의사 있습니다. 추천해요!', author: '이**' },
    { id: 'review3', rating: 4, content: '가격 대비 좋은 것 같아요.', author: '박**' },
  ],
}

export const DEFAULT_ICON_LIST = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ffffff',
  height: 'auto',
  showTitle: true,
  title: '주요 특징',
  titleSize: '28',
  titleWeight: '700',
  titleColor: '#000000',
  layout: 'vertical',
  iconSize: '24',
  iconColor: '#22c55e',
  textColor: '#333333',
  textSize: '16',
  gap: '16px',
  items: [
    { id: 'icon1', icon: '✓', text: '무료 배송' },
    { id: 'icon2', icon: '✓', text: '30일 무료 반품' },
    { id: 'icon3', icon: '✓', text: '1년 품질 보증' },
    { id: 'icon4', icon: '✓', text: '24시간 고객 지원' },
  ],
}

export const DEFAULT_STICKY_BAR = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ffffff',
  height: '70px',
  showPrice: true,
  priceLabel: '판매가',
  price: '29,900원',
  priceSize: '24',
  priceColor: '#ef4444',
  buttonText: '구매하기',
  buttonSize: '16',
  buttonWeight: '600',
  buttonColor: '#ffffff',
  buttonBgColor: '#000000',
  buttonBorderRadius: '8px',
}

export const DEFAULT_QUOTE = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#f9fafb',
  height: 'auto',
  style: 'quote',
  text: '고객의 소리를 담은 인용문이나 중요한 메시지를 여기에 작성하세요.',
  textSize: '20',
  textWeight: '500',
  textColor: '#333333',
  showAuthor: true,
  author: '- 고객명',
  authorColor: '#666666',
  borderColor: '#3b82f6',
  borderWidth: '4px',
  iconColor: '#3b82f6',
}

export const DEFAULT_IMAGE_GALLERY = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ffffff',
  height: 'auto',
  images: [
    { id: 'img1', url: 'https://via.placeholder.com/600x600/3b82f6/ffffff?text=Image+1', alt: '이미지 1' },
    { id: 'img2', url: 'https://via.placeholder.com/600x600/22c55e/ffffff?text=Image+2', alt: '이미지 2' },
    { id: 'img3', url: 'https://via.placeholder.com/600x600/ef4444/ffffff?text=Image+3', alt: '이미지 3' },
  ],
  thumbnailSize: '80px',
  thumbnailGap: '8px',
  mainImageHeight: '500px',
  showThumbnails: true,
  thumbnailPosition: 'bottom',
  enableZoom: true,
  zoomScale: 2,
}

export const DEFAULT_TRUST_BADGE = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#f9fafb',
  height: 'auto',
  layout: 'horizontal',
  gap: '24px',
  showTitle: false,
  title: '안심 쇼핑',
  titleSize: '20',
  titleWeight: '600',
  titleColor: '#000000',
  badges: [
    { id: 'badge1', icon: '🔒', text: '안전결제', subtext: 'SSL 보안 적용' },
    { id: 'badge2', icon: '✓', text: '정품보증', subtext: '100% 정품만 취급' },
    { id: 'badge3', icon: '🔄', text: '교환/반품', subtext: '30일 이내 무료' },
    { id: 'badge4', icon: '📞', text: '고객센터', subtext: '24시간 상담 가능' },
  ],
  iconSize: '32',
  iconColor: '#3b82f6',
  textColor: '#000000',
  textSize: '14',
  subtextColor: '#666666',
  subtextSize: '12',
  badgeBgColor: '#ffffff',
  badgeBorderColor: '#e5e7eb',
  badgeBorderRadius: '8px',
}

export const DEFAULT_SHIPPING = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#ffffff',
  height: 'auto',
  showIcon: true,
  iconType: 'truck',
  iconColor: '#3b82f6',
  iconSize: '24',
  title: '배송 안내',
  titleSize: '18',
  titleWeight: '600',
  titleColor: '#000000',
  items: [
    { id: 'ship1', label: '배송비', value: '무료배송' },
    { id: 'ship2', label: '배송 예정일', value: '오늘 출발 시 내일 도착' },
    { id: 'ship3', label: '배송 방법', value: 'CJ대한통운' },
  ],
  labelColor: '#666666',
  valueColor: '#000000',
  textSize: '14',
  borderColor: '#e5e7eb',
  borderStyle: 'solid',
  borderRadius: '8px',
}

export const DEFAULT_NOTICE_BANNER = {
  ...DEFAULT_SECTION_HEADER,
  backgroundColor: '#fef3c7',
  height: 'auto',
  style: 'promotion',
  showIcon: true,
  icon: '🎉',
  iconColor: '#f59e0b',
  text: '지금 구매하시면 10% 추가 할인!',
  textSize: '16',
  textWeight: '600',
  textColor: '#92400e',
  showButton: true,
  buttonText: '쿠폰 받기',
  buttonColor: '#ffffff',
  buttonBgColor: '#f59e0b',
  buttonBorderRadius: '4px',
  closable: false,
  borderRadius: '8px',
}
